import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.io.File;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class studentRegister extends javax.swing.JFrame {

    /**
     * Creates new form studentRegister
     */
    private boolean isMuted = false;
    private Clip successClip;
    public studentRegister() {
        initComponents();
        Connect();
        playSound();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void playSound() {
    try {
        File soundFile = new File("C:\\Users\\Paul Justin\\Documents\\NetBeansProjects\\ITEC PROJ\\src\\Images\\bgmusc.wav");
        if (soundFile.exists()) {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile);
            successClip = AudioSystem.getClip(); // Assign to the class-level variable
            successClip.open(audioInputStream);
            successClip.loop(Clip.LOOP_CONTINUOUSLY);
            successClip.start();
        } else {
            System.out.println("Sound file does not exist.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    public void Connect(){
    
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gradingsystem","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
//       private void LoadInfoStudent(){
//     
//        try {
//
//            // Write your SQL quer
//            String stuNum = txt_sturegnum.getText();
//            // Create a PreparedStatement
//            pst = con.prepareStatement("SELECT * FROM studentinfo_tbl WHERE stu_Num = ?");
//            pst.setString(1, stuNum);
//            // Execute the query and retrieve the result set
//            rs = pst.executeQuery();
//            
//            // Process the result set
//            while (rs.next()) {
//
//                    
//                        
//                    
////                    sectionComboBox.addItem(rs.getString(10));
////                    sectionComboBox.addItem(rs.getString(11));
////                    sectionComboBox.addItem(rs.getString(12));
//                    
//                    
//                    txt_sturegfname.setText(rs.getString(3));
//                    txt_sturegmname.setText(rs.getString(4));
//                    txt_stureglname.setText(rs.getString(5));
//                    txt_sturegbday.setText(rs.getString(6));
//                    txt_sturegcontact.setText(rs.getString(8));
//                    txt_sturegem.setText(rs.getString(9));
//                    txt_sturegpass.setText(rs.getString(10));
//                    
//                    cmb_sturegdept.setSelectedItem(rs.getString(11));
//                    cmb_stureggrade.setSelectedItem(rs.getString(12));
//                    cmb_sturegsec.setSelectedItem(rs.getString(13));
//                    cmb_stureggender.setSelectedItem(rs.getString(7));
//
//                } 
//                
//
//        } catch (SQLException e) {
//
//        } 
//    
//    
//    
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_sturegnum = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        cmb_sturegdept = new javax.swing.JComboBox<>();
        cmb_stureggrade = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cmb_sturegsec = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmb_sem = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_sturegmname = new javax.swing.JTextField();
        txt_sturegpass = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        txt_sturegem = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_sturegcontact = new javax.swing.JTextField();
        cmb_stureggender = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        txt_sturegbday = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_stureglname = new javax.swing.JTextField();
        txt_sturegfname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jPanel13.setBackground(new java.awt.Color(77, 77, 77));
        jPanel13.setPreferredSize(new java.awt.Dimension(26, 26));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student No:");
        jPanel13.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Registration");
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(1600, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 150)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(63, 171, 46));
        jLabel13.setText("IMUS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 410, 170));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 154)); // NOI18N
        jLabel10.setText("IMUS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 410, 170));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cvsu logo.png"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 340, 300));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(63, 171, 46));
        jLabel31.setText("Cavite State University");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 450, 60));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel32.setText("Cavite State University");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 440, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Students.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 560));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_update.setBackground(new java.awt.Color(25, 149, 73));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update Info");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, 110, -1));

        jButton1.setBackground(new java.awt.Color(77, 77, 77));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 110, -1));

        jButton3.setBackground(new java.awt.Color(77, 77, 77));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Insert Subs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student No:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 30));

        txt_sturegnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sturegnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sturegnumFocusGained(evt);
            }
        });
        txt_sturegnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sturegnumActionPerformed(evt);
            }
        });
        txt_sturegnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sturegnumKeyReleased(evt);
            }
        });
        jPanel1.add(txt_sturegnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 360, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Program:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 30));

        cmb_sturegdept.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_sturegdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CS", "FM" }));
        cmb_sturegdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sturegdeptActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_sturegdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 360, -1));

        cmb_stureggrade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_stureggrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(cmb_stureggrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 360, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Year:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Section:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 30));

        cmb_sturegsec.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_sturegsec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        cmb_sturegsec.setRequestFocusEnabled(false);
        jPanel1.add(cmb_sturegsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 360, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Semester:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 30));

        cmb_sem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_sem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jPanel1.add(cmb_sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 360, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("First Name:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Middle Initial:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 100, 30));

        txt_sturegmname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_sturegmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 360, -1));

        txt_sturegpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txt_sturegpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 360, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Password:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, 30));

        txt_sturegem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sturegem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sturegemFocusGained(evt);
            }
        });
        txt_sturegem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sturegemActionPerformed(evt);
            }
        });
        txt_sturegem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sturegemKeyReleased(evt);
            }
        });
        jPanel1.add(txt_sturegem, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 360, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Email:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Contact:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, 30));

        txt_sturegcontact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sturegcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sturegcontactActionPerformed(evt);
            }
        });
        txt_sturegcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_sturegcontactKeyReleased(evt);
            }
        });
        jPanel1.add(txt_sturegcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 360, -1));

        cmb_stureggender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_stureggender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmb_stureggender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_stureggenderActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_stureggender, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 360, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sex:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, 30));

        txt_sturegbday.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sturegbday.setText("YYYY/MM/DD");
        txt_sturegbday.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_sturegbdayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_sturegbdayFocusLost(evt);
            }
        });
        txt_sturegbday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sturegbdayActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sturegbday, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 360, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Birthday:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, 30));
        jPanel1.add(txt_stureglname, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 360, -1));

        txt_sturegfname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_sturegfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sturegfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sturegfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 360, -1));

        jPanel2.setBackground(new java.awt.Color(63, 171, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Student Registration");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 70));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 70));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Last Name:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(63, 171, 46));
        jLabel29.setText("Cavite State University");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 550, 60));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel30.setText("Cavite State University");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 530, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 1090, 560));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 150)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(63, 171, 46));
        jLabel14.setText("IMUS");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 410, 170));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 154)); // NOI18N
        jLabel11.setText("IMUS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 410, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        successClip.stop();
        new teacherMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_sturegfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sturegfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sturegfnameActionPerformed

    private void txt_sturegbdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sturegbdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sturegbdayActionPerformed

    private void txt_sturegbdayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sturegbdayFocusLost
        // TODO add your handling code here:
        String sturBday = txt_sturegbday.getText();
        if(txt_sturegbday.getText().equals("")){
            txt_sturegbday.setText("YYYY/MM/DD");
            txt_sturegbday.setForeground(new Color(153,153,153));
        } else if (sturBday.matches("^\\d{4}/\\d{2}/\\d{2}$")) {
            txt_sturegbday.setBackground(new Color(159, 226, 191)); // Valid format: Set background to green
        } else {
            txt_sturegbday.setBackground(new Color(255, 120, 120)); // Invalid format: Set background to red
        }
    }//GEN-LAST:event_txt_sturegbdayFocusLost

    private void txt_sturegbdayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sturegbdayFocusGained
        // TODO add your handling code here:
        if(txt_sturegbday.getText().equals("YYYY/MM/DD")){
            txt_sturegbday.setText("");
            txt_sturegbday.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txt_sturegbdayFocusGained

    private void cmb_stureggenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_stureggenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_stureggenderActionPerformed

    private void txt_sturegcontactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sturegcontactKeyReleased
        String phoneNum = txt_sturegcontact.getText();

        if(phoneNum.matches("^[0-9]*$") && phoneNum.length()==11){

            txt_sturegcontact.setBackground(new Color(159,226, 191));

        }else {

            txt_sturegcontact.setBackground(new Color(255,120,120));
        }
    }//GEN-LAST:event_txt_sturegcontactKeyReleased

    private void txt_sturegcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sturegcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sturegcontactActionPerformed

    private void txt_sturegemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sturegemKeyReleased
        String sturEmail = txt_sturegem.getText();

        if(sturEmail.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")){

            txt_sturegem.setBackground(new Color(159,226, 191));

        }else {

            txt_sturegem.setBackground(new Color(255,120,120));
        }
    }//GEN-LAST:event_txt_sturegemKeyReleased

    private void txt_sturegemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sturegemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sturegemActionPerformed

    private void txt_sturegemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sturegemFocusGained

    }//GEN-LAST:event_txt_sturegemFocusGained

    private void cmb_sturegdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sturegdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sturegdeptActionPerformed

    private void txt_sturegnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sturegnumKeyReleased
        // TODO add your handling code here:
        String sturegnum = txt_sturegnum.getText();

        if(sturegnum.matches("^[0-9]*$") && sturegnum.length()==9){

            txt_sturegnum.setBackground(new Color(159,226, 191));

        }else {

            txt_sturegnum.setBackground(new Color(255,120,120));
        }

        try {

            // Write your SQL quer
            String stuNum = txt_sturegnum.getText();
            // Create a PreparedStatement
            pst = con.prepareStatement("SELECT * FROM studentinfo_tbl WHERE stu_Num = ?");
            pst.setString(1, stuNum);
            // Execute the query and retrieve the result set
            rs = pst.executeQuery();

            // Process the result set
            if (rs.next()) {

                //                    sectionComboBox.addItem(rs.getString(10));
                //                    sectionComboBox.addItem(rs.getString(11));
                //                    sectionComboBox.addItem(rs.getString(12));

                txt_sturegfname.setText(rs.getString(3));
                txt_sturegmname.setText(rs.getString(4));
                txt_stureglname.setText(rs.getString(5));
                txt_sturegbday.setText(rs.getString(6));
                txt_sturegcontact.setText(rs.getString(8));
                txt_sturegem.setText(rs.getString(9));
                txt_sturegpass.setText(rs.getString(10));

                cmb_sturegdept.setSelectedItem(rs.getString(11));
                cmb_stureggrade.setSelectedItem(rs.getString(12));
                cmb_sturegsec.setSelectedItem(rs.getString(13));
                cmb_stureggender.setSelectedItem(rs.getString(7));

            } else {

                txt_sturegfname.setText("");
                txt_sturegmname.setText("");
                txt_stureglname.setText("");
                txt_sturegbday.setText("");
                txt_sturegcontact.setText("");
                txt_sturegem.setText("");
                txt_sturegpass.setText("");

                cmb_sturegdept.setSelectedItem(rs.getString(11));
                cmb_stureggrade.setSelectedItem(rs.getString(12));
                cmb_sturegsec.setSelectedItem(rs.getString(13));
                cmb_stureggender.setSelectedItem(rs.getString(7));

            }

        } catch (SQLException e) {

        }
    }//GEN-LAST:event_txt_sturegnumKeyReleased

    private void txt_sturegnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sturegnumActionPerformed
        // TODO add your handling code here:
        String sturegnum = txt_sturegnum.getText();

        if(sturegnum.matches("^[0-9]*$") && sturegnum.length()==9){

            txt_sturegnum.setBackground(new Color(159,226, 191));

        }else {

            txt_sturegnum.setBackground(new Color(255,120,120));
        }
    }//GEN-LAST:event_txt_sturegnumActionPerformed

    private void txt_sturegnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_sturegnumFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sturegnumFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //        try {
            //            String sturegnum = txt_sturegnum.getText();
            //            String stureggrade = cmb_stureggrade.getSelectedItem().toString();
            //            String sturegsection = cmb_sturegsec.getSelectedItem().toString();
            //            String sturegfname = txt_sturegfname.getText();
            //            String sturegmname = txt_sturegmname.getText();
            //            String stureglname = txt_stureglname.getText();
            //            String sturegbday = txt_sturegbday.getText();
            //            String stureggender = cmb_stureggender.getSelectedItem().toString();
            //            String sturegcontact = txt_sturegcontact.getText();
            //            String sturegem = txt_sturegem.getText();
            //            String sturegpass = txt_sturegpass.getText();
            //            String sturegdept = cmb_sturegdept.getSelectedItem().toString();
            //            String stregsem = cmb_sem.getSelectedItem().toString();
            //
            //            boolean isValidStudentNum = sturegnum.matches("^[0-9]*$") && sturegnum.length() == 9;
            //            boolean isValidContactNum = sturegcontact.matches("^[0-9]*$") && sturegcontact.length() == 11;
            //            boolean isValidEmail = sturegem.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$");
            //
            //
            //            String query = "SELECT * FROM subject_tbl WHERE stu_Grade = ? AND sem_Num = ? AND stu_Dept = ?";
            //            pst = con.prepareStatement(query);
            //            pst.setString(1, stureggrade);
            //            pst.setString(2, stregsem);
            //            pst.setString(3, sturegdept);
            //            rs = pst.executeQuery();
            //            String selectedSub = rs.getString("sub_Name");
            //
            //            String que = "SELECT * FROM "+selectedSub+"_tbl"+" WHERE stu_Grade = ? AND sem_Num = ? AND stu_Dept = ?";
            //            PreparedStatement tryi = con.prepareStatement(que);
            //            tryi.setString(1, stureggrade);
            //            tryi.setString(2, stregsem);
            //            tryi.setString(3, sturegdept);
            //            ResultSet ohe = pst.executeQuery();
            //
            //            if (!isValidStudentNum || !isValidContactNum || !isValidEmail) {
                //            // Show error message
                //            JOptionPane.showMessageDialog(this, "Please correct the highlighted fields.", "Error", JOptionPane.ERROR_MESSAGE);
                //            // Exit the method if validation fails
                //        } else {
                //            // Clear existing items in studentComboBox
                //
                //            // Add retrieved student IDs to studentComboBox
                //            while (ohe.next()) {
                    //
                    //
                    //                PreparedStatement pstSub = con.prepareStatement("INSERT INTO "+selectedSub+"_tbl"+" (stu_Num, stu_Grade, stu_Sect, stu_Fname, stu_Lname, q1, q2, q3, l1, l2, l3, mid, fin, qave, lave, eave,stu_Dept,fingrade) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    //                pstSub.setString(1, sturegnum);
                    //                pstSub.setString(2, stureggrade);
                    //                pstSub.setString(3, sturegsection);
                    //                pstSub.setString(4, sturegfname);
                    //                pstSub.setString(5, stureglname);
                    //                pstSub.setString(6, "0");
                    //                pstSub.setString(7, "0");
                    //                pstSub.setString(8, "0");
                    //                pstSub.setString(9, "0");
                    //                pstSub.setString(10, "0");
                    //                pstSub.setString(11, "0");
                    //                pstSub.setString(12, "0");
                    //                pstSub.setString(13, "0");
                    //                pstSub.setString(14, "0");
                    //                pstSub.setString(15, "0");
                    //                pstSub.setString(16, "0");
                    //                pstSub.setString(17, sturegdept);
                    //                pstSub.setString(18, "0");
                    //
                    //                int kSub= pstSub.executeUpdate();
                    //
                    //                while ( kSub == 1 ) {
                        //                    JOptionPane.showMessageDialog(this, "Data Added Successfully!");
                        //                    break;
                        //                }
                    ////                    else {
                        ////                    JOptionPane.showMessageDialog(this, "Data Not Recorded!");
                        ////                }
                    //
                    //            }
                //
                //        }
            //        } catch (SQLException ex) {
            //            Logger.getLogger(studentRegister.class.getName()).log(Level.SEVERE, null, ex);
            //        }

        try {
            String sturegnum = txt_sturegnum.getText();
            String stureggrade = cmb_stureggrade.getSelectedItem().toString();
            String sturegsection = cmb_sturegsec.getSelectedItem().toString();
            String sturegfname = txt_sturegfname.getText();
            String sturegmname = txt_sturegmname.getText();
            String stureglname = txt_stureglname.getText();
            String sturegbday = txt_sturegbday.getText();
            String stureggender = cmb_stureggender.getSelectedItem().toString();
            String sturegcontact = txt_sturegcontact.getText();
            String sturegem = txt_sturegem.getText();
            String sturegpass = txt_sturegpass.getText();
            String sturegdept = cmb_sturegdept.getSelectedItem().toString();
            String stregsem = cmb_sem.getSelectedItem().toString();

            boolean isValidStudentNum = sturegnum.matches("^[0-9]*$") && sturegnum.length() == 9;
            boolean isValidContactNum = sturegcontact.matches("^[0-9]*$") && sturegcontact.length() == 11;
            boolean isValidEmail = sturegem.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$");

            //        PreparedStatement pstCheck = con.prepareStatement("SELECT stu_Num, stu_Em FROM studentinfo_tbl WHERE stu_Num = ? OR stu_Em = ?");
            //        pstCheck.setString(1, sturegnum);
            //        pstCheck.setString(2, sturegem);
            //
            //        ResultSet rsCheck = pstCheck.executeQuery();

            if (!isValidStudentNum || !isValidContactNum || !isValidEmail) {
                // Show error message
                JOptionPane.showMessageDialog(this, "Please correct the highlighted fields.", "Error", JOptionPane.ERROR_MESSAGE);
                // Exit the method if validation fails
            }

            //        else if (rsCheck.next()) {
                //                JOptionPane.showMessageDialog(this, "Student number or Email already exists!");
                //        }

            else {

                //                PreparedStatement pstStudent = con.prepareStatement("INSERT INTO studentinfo_tbl (stu_Num, stu_Grade, stu_Sect, stu_Fname, stu_Mname, stu_Lname, stu_Bday, stu_Gender, stu_Cpno, stu_Em, stu_Pass,stu_Dept) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
                //                pstStudent.setString(1, sturegnum);
                //                pstStudent.setString(2, stureggrade);
                //                pstStudent.setString(3, sturegsection);
                //                pstStudent.setString(4, sturegfname);
                //                pstStudent.setString(5, sturegmname);
                //                pstStudent.setString(6, stureglname);
                //                pstStudent.setString(7, sturegbday);
                //                pstStudent.setString(8, stureggender);
                //                pstStudent.setString(9, sturegcontact);
                //                pstStudent.setString(10, sturegem);
                //                pstStudent.setString(11, sturegpass);
                //                pstStudent.setString(12, sturegdept);
                //
                //                int kStudent = pstStudent.executeUpdate();

                // Insert into quiz_tbl
                String query = "SELECT * FROM subject_tbl WHERE stu_Grade = ? AND sem_Num = ? AND stu_Dept = ?";
                pst = con.prepareStatement(query);
                pst.setString(1, stureggrade);
                pst.setString(2, stregsem);
                pst.setString(3, sturegdept);
                rs = pst.executeQuery();
                //
                //                // Clear existing items in studentComboBox
                //
                //                // Add retrieved student IDs to studentComboBox
                while (rs.next()) {
                    String selectedSub = rs.getString("sub_Name");

                    PreparedStatement pstSub = con.prepareStatement("INSERT INTO "+selectedSub+"_tbl"+" (stu_Num, stu_Grade, stu_Sect, stu_Fname, stu_Lname, q1, q2, q3, l1, l2, l3, mid, fin, qave, lave, eave,stu_Dept,fingrade) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    pstSub.setString(1, sturegnum);
                    pstSub.setString(2, stureggrade);
                    pstSub.setString(3, sturegsection);
                    pstSub.setString(4, sturegfname);
                    pstSub.setString(5, stureglname);
                    pstSub.setString(6, "0");
                    pstSub.setString(7, "0");
                    pstSub.setString(8, "0");
                    pstSub.setString(9, "0");
                    pstSub.setString(10, "0");
                    pstSub.setString(11, "0");
                    pstSub.setString(12, "0");
                    pstSub.setString(13, "0");
                    pstSub.setString(14, "0");
                    pstSub.setString(15, "0");
                    pstSub.setString(16, "0");
                    pstSub.setString(17, sturegdept);
                    pstSub.setString(18, "0");

                    int kSub= pstSub.executeUpdate();

                    while ( kSub == 1 ) {
                        JOptionPane.showMessageDialog(this, "Data Added Successfully!");
                        break;
                    }
                    ////                    else {
                        ////                    JOptionPane.showMessageDialog(this, "Data Not Recorded!");
                        ////                }

                }

                // Close the connection

                //                if (kStudent == 1) {
                    //                    JOptionPane.showMessageDialog(this, "Data Added Successfully!");
                    //                } else {
                    //                    JOptionPane.showMessageDialog(this, "Data Not Recorded!");
                    //                }
                //
                //                txt_sturegnum.setText("");
                //                cmb_stureggrade.setSelectedIndex(0);  // Assuming index 0 is the default selection
                //                cmb_sturegsec.setSelectedIndex(0);
                //                txt_sturegfname.setText("");
                //                txt_sturegmname.setText("");
                //                txt_stureglname.setText("");
                //                txt_sturegbday.setText("");
                //                cmb_stureggender.setSelectedIndex(0);
                //                txt_sturegcontact.setText("");
                //                txt_sturegem.setText("");
                //                txt_sturegpass.setText("");
                //
                //
                //
                //
            }

        } catch (SQLException ex) {
            Logger.getLogger(studentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            String sturegnum = txt_sturegnum.getText();
            String stureggrade = cmb_stureggrade.getSelectedItem().toString();
            String sturegsection = cmb_sturegsec.getSelectedItem().toString();
            String sturegfname = txt_sturegfname.getText();
            String sturegmname = txt_sturegmname.getText();
            String stureglname = txt_stureglname.getText();
            String sturegbday = txt_sturegbday.getText();
            String stureggender = cmb_stureggender.getSelectedItem().toString();
            String sturegcontact = txt_sturegcontact.getText();
            String sturegem = txt_sturegem.getText();
            String sturegpass = txt_sturegpass.getText();
            String sturegdept = cmb_sturegdept.getSelectedItem().toString();
            String stregsem = cmb_sem.getSelectedItem().toString();

            boolean isValidStudentNum = sturegnum.matches("^[0-9]*$") && sturegnum.length() == 9;
            boolean isValidContactNum = sturegcontact.matches("^[0-9]*$") && sturegcontact.length() == 11;
            boolean isValidEmail = sturegem.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$");

            PreparedStatement pstCheck = con.prepareStatement("SELECT stu_Num, stu_Em FROM studentinfo_tbl WHERE stu_Num = ? OR stu_Em = ?");
            pstCheck.setString(1, sturegnum);
            pstCheck.setString(2, sturegem);

            ResultSet rsCheck = pstCheck.executeQuery();

            if (!isValidStudentNum || !isValidContactNum || !isValidEmail) {
                // Show error message
                JOptionPane.showMessageDialog(this, "Please correct the highlighted fields.", "Error", JOptionPane.ERROR_MESSAGE);
                // Exit the method if validation fails
            } else if (rsCheck.next()) {
                JOptionPane.showMessageDialog(this, "Student number or Email already exists!");
            } else {

                PreparedStatement pstStudent = con.prepareStatement("INSERT INTO studentinfo_tbl (stu_Num, stu_Grade, stu_Sect, stu_Fname, stu_Mname, stu_Lname, stu_Bday, stu_Gender, stu_Cpno, stu_Em, stu_Pass,stu_Dept) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
                pstStudent.setString(1, sturegnum);
                pstStudent.setString(2, stureggrade);
                pstStudent.setString(3, sturegsection);
                pstStudent.setString(4, sturegfname);
                pstStudent.setString(5, sturegmname);
                pstStudent.setString(6, stureglname);
                pstStudent.setString(7, sturegbday);
                pstStudent.setString(8, stureggender);
                pstStudent.setString(9, sturegcontact);
                pstStudent.setString(10, sturegem);
                pstStudent.setString(11, sturegpass);
                pstStudent.setString(12, sturegdept);

                int kStudent = pstStudent.executeUpdate();

                // Insert into quiz_tbl
                String query = "SELECT * FROM subject_tbl WHERE stu_Grade = ? AND sem_Num = ? AND stu_Dept = ?";
                pst = con.prepareStatement(query);
                pst.setString(1, stureggrade);
                pst.setString(2, stregsem);
                pst.setString(3, sturegdept);
                rs = pst.executeQuery();
                //
                //                // Clear existing items in studentComboBox
                //
                //                // Add retrieved student IDs to studentComboBox
                //                while (rs.next()) {
                    //                    String selectedSub = rs.getString("sub_Name");
                    //
                    //                    PreparedStatement pstSub = con.prepareStatement("INSERT INTO "+selectedSub+"_tbl"+" (stu_Num, stu_Grade, stu_Sect, stu_Fname, stu_Lname, q1, q2, q3, l1, l2, l3, mid, fin, qave, lave, eave,stu_Dept,fingrade) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
                    //                    pstSub.setString(1, sturegnum);
                    //                    pstSub.setString(2, stureggrade);
                    //                    pstSub.setString(3, sturegsection);
                    //                    pstSub.setString(4, sturegfname);
                    //                    pstSub.setString(5, stureglname);
                    //                    pstSub.setString(6, "0");
                    //                    pstSub.setString(7, "0");
                    //                    pstSub.setString(8, "0");
                    //                    pstSub.setString(9, "0");
                    //                    pstSub.setString(10, "0");
                    //                    pstSub.setString(11, "0");
                    //                    pstSub.setString(12, "0");
                    //                    pstSub.setString(13, "0");
                    //                    pstSub.setString(14, "0");
                    //                    pstSub.setString(15, "0");
                    //                    pstSub.setString(16, "0");
                    //                    pstSub.setString(17, sturegdept);
                    //                    pstSub.setString(18, "0");
                    //
                    //                    int kSub= pstSub.executeUpdate();
                    //
                    //                    while ( kSub == 1 ) {
                        //                    JOptionPane.showMessageDialog(this, "Data Added Successfully!");
                        //                    break;
                        //                }
                    ////                    else {
                        ////                    JOptionPane.showMessageDialog(this, "Data Not Recorded!");
                        ////                }
                    //
                    //                }

                // Close the connection

                if (kStudent == 1) {
                    JOptionPane.showMessageDialog(this, "Data Added Successfully!");
                } else {
                    JOptionPane.showMessageDialog(this, "Data Not Recorded!");
                }

                txt_sturegnum.setText("");
                cmb_stureggrade.setSelectedIndex(0);  // Assuming index 0 is the default selection
                cmb_sturegsec.setSelectedIndex(0);
                txt_sturegfname.setText("");
                txt_sturegmname.setText("");
                txt_stureglname.setText("");
                txt_sturegbday.setText("");
                cmb_stureggender.setSelectedIndex(0);
                txt_sturegcontact.setText("");
                txt_sturegem.setText("");
                txt_sturegpass.setText("");

            }

        } catch (SQLException ex) {
            Logger.getLogger(studentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            String sturegnum = txt_sturegnum.getText();
            String stureggrade = cmb_stureggrade.getSelectedItem().toString();
            String sturegsection = cmb_sturegsec.getSelectedItem().toString();
            String sturegfname = txt_sturegfname.getText();
            String sturegmname = txt_sturegmname.getText();
            String stureglname = txt_stureglname.getText();
            String sturegbday = txt_sturegbday.getText();
            String stureggender = cmb_stureggender.getSelectedItem().toString();
            String sturegcontact = txt_sturegcontact.getText();
            String sturegem = txt_sturegem.getText();
            String sturegpass = txt_sturegpass.getText();
            String sturegdept = cmb_sturegdept.getSelectedItem().toString();

            pst = con.prepareStatement("UPDATE studentinfo_tbl SET stu_Num=?, stu_Grade=?, stu_Sect=?, stu_Fname=?, stu_Mname=?, stu_Lname=?, stu_Bday=?, stu_Gender=?, stu_Cpno=?,stu_Em=?, stu_Dept=?, stu_Pass = ? WHERE stu_Num=?");
            pst.setString(1, sturegnum);
            pst.setString(2, stureggrade);
            pst.setString(3, sturegsection);
            pst.setString(4, sturegfname);
            pst.setString(5, sturegmname);
            pst.setString(6, stureglname);
            pst.setString(7, sturegbday);
            pst.setString(8, stureggender);
            pst.setString(9, sturegcontact);
            pst.setString(10, sturegem);
            pst.setString(11, sturegdept);
            pst.setString(12, sturegpass);

            // Set value for the 11th parameter
            pst.setString(13, sturegnum);

            int k = pst.executeUpdate();

            if (k==1){

                JOptionPane.showMessageDialog(this,"Record Updated Succeessfully!");
                txt_sturegnum.setText("");
                txt_sturegpass.setText("");
                txt_sturegem.setText("");
                txt_sturegbday.setText("");
                txt_stureglname.setText("");
                txt_sturegfname.setText("");
                txt_sturegmname.setText("");
                txt_sturegcontact.setText("");

                txt_sturegnum.requestFocus();

            } else{

                JOptionPane.showMessageDialog(this,"Record Failed to Update!");

            }

        } catch (SQLException ex) {
            Logger.getLogger(teacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed
    
  

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cmb_sem;
    private javax.swing.JComboBox<String> cmb_sturegdept;
    private javax.swing.JComboBox<String> cmb_stureggender;
    private javax.swing.JComboBox<String> cmb_stureggrade;
    private javax.swing.JComboBox<String> cmb_sturegsec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_sturegbday;
    private javax.swing.JTextField txt_sturegcontact;
    private javax.swing.JTextField txt_sturegem;
    private javax.swing.JTextField txt_sturegfname;
    private javax.swing.JTextField txt_stureglname;
    private javax.swing.JTextField txt_sturegmname;
    private javax.swing.JTextField txt_sturegnum;
    private javax.swing.JPasswordField txt_sturegpass;
    // End of variables declaration//GEN-END:variables
}
