import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.io.File;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class studentLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form studentLogin
     */
    private boolean isMuted = false;
    private Clip successClip;
    public studentLogin() {
        initComponents();
        Connect();
        playSound();
    }
    private void playSound() {
    try {
        File soundFile = new File("C:\\Users\\Paul Justin\\Documents\\NetBeansProjects\\ITEC PROJ\\src\\Images\\bgmusc.wav");
        if (soundFile.exists()) {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile);
            successClip = AudioSystem.getClip(); // Assign to the class-level variable
            successClip.open(audioInputStream);
            successClip.loop(Clip.LOOP_CONTINUOUSLY);
            successClip.start();
        } else {
            System.out.println("Sound file does not exist.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void Connect(){
    
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gradingsystem","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_stuem = new javax.swing.JTextField();
        txt_stupass = new javax.swing.JPasswordField();
        btn_stulogin = new javax.swing.JButton();
        go_tealogin = new javax.swing.JButton();
        go_adlogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT LOGIN");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        txt_stuem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_stuem.setMinimumSize(new java.awt.Dimension(64, 24));
        txt_stuem.setPreferredSize(new java.awt.Dimension(64, 24));
        txt_stuem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_stuemActionPerformed(evt);
            }
        });
        getContentPane().add(txt_stuem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, 30));

        txt_stupass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_stupass.setPreferredSize(new java.awt.Dimension(64, 24));
        getContentPane().add(txt_stupass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 30));

        btn_stulogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_stulogin.setText("Log in");
        btn_stulogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stuloginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_stulogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 90, -1));

        go_tealogin.setBackground(new java.awt.Color(63, 171, 46));
        go_tealogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        go_tealogin.setForeground(new java.awt.Color(255, 255, 255));
        go_tealogin.setText("Teacher");
        go_tealogin.setBorderPainted(false);
        go_tealogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_tealoginActionPerformed(evt);
            }
        });
        getContentPane().add(go_tealogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        go_adlogin.setBackground(new java.awt.Color(63, 171, 46));
        go_adlogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        go_adlogin.setForeground(new java.awt.Color(255, 255, 255));
        go_adlogin.setText("Admin");
        go_adlogin.setBorderPainted(false);
        go_adlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_adloginActionPerformed(evt);
            }
        });
        getContentPane().add(go_adlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Log in Page");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 140, 90));

        jToggleButton1.setText("🔈");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cvsu.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cloud.gif"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 600, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_stuemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_stuemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_stuemActionPerformed

    private void btn_stuloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stuloginActionPerformed
        String stuem = txt_stuem.getText();
        String stupass = new String(txt_stupass.getPassword());       
        
        try {
            PreparedStatement pstLog = con.prepareStatement("SELECT * FROM studentinfo_tbl WHERE stu_Em = ?");
            pstLog.setString(1, stuem);
            rs = pstLog.executeQuery();
            
            if (rs.next()) {
            String em = rs.getString("stu_Em");
            String password = rs.getString("stu_Pass");

            if ((stuem.equals(em)) && stupass.equals(password)) {
                JOptionPane.showMessageDialog(null, "SUCCESS");

                // Insert the email into tealogin_tbl
                try {
                    PreparedStatement pstInsert = con.prepareStatement("INSERT INTO stulogin_tbl (stu_Em) VALUES (?)");
                    pstInsert.setString(1, stuem);
                    pstInsert.executeUpdate();
                } catch (SQLException ex) {
                    // Handle the exception, e.g., display an error message
                    ex.printStackTrace();
                }

                new studentMain().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "INCORRECT!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User not found!");
        }
            
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btn_stuloginActionPerformed

    private void go_tealoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_tealoginActionPerformed
        successClip.stop();
        new teacherLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_go_tealoginActionPerformed

    private void go_adloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_adloginActionPerformed
        successClip.stop();
        new adminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_go_adloginActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            // If the toggle button is selected, mute
            successClip.stop();
            isMuted = true;
            jToggleButton1.setText("🔇");
        } else {
            // If the toggle button is not selected, unmute
            successClip.loop(Clip.LOOP_CONTINUOUSLY);
            isMuted = false;
            jToggleButton1.setText("🔈");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_stulogin;
    private javax.swing.JButton go_adlogin;
    private javax.swing.JButton go_tealogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txt_stuem;
    private javax.swing.JPasswordField txt_stupass;
    // End of variables declaration//GEN-END:variables
}
