import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import java.io.File;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class teacherLogin extends javax.swing.JFrame {

    /**
     * Creates new form teacherLogin
     */
    private boolean isMuted = false;
    private Clip successClip;
    public teacherLogin() {
        initComponents();
        Connect();
        playSound();
    }
    
    private void playSound() {
    try {
        File soundFile = new File("C:\\Users\\Paul Justin\\Documents\\NetBeansProjects\\ITEC PROJ\\src\\Images\\bgmusc.wav");
        if (soundFile.exists()) {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(soundFile);
            successClip = AudioSystem.getClip(); // Assign to the class-level variable
            successClip.open(audioInputStream);
            successClip.loop(Clip.LOOP_CONTINUOUSLY);
            successClip.start();
        } else {
            System.out.println("Sound file does not exist.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    public JTextField getTxt_teaem() {
        return txt_teaem;
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect(){
    
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gradingsystem","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_teaem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_tealogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        txt_teapass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Log in Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        txt_teaem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txt_teaem, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 190, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 50));

        btn_tealogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tealogin.setText("Log in");
        btn_tealogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tealoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tealogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teacher.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, 110));

        jButton1.setBackground(new java.awt.Color(63, 171, 46));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jButton2.setBackground(new java.awt.Color(63, 171, 46));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 310, 90, -1));

        jToggleButton1.setText("🔈");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        txt_teapass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_teapass.setPreferredSize(new java.awt.Dimension(64, 24));
        getContentPane().add(txt_teapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cvsu.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cloud.gif"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tealoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tealoginActionPerformed
    String teaem = txt_teaem.getText();
    String teapass = new String(txt_teapass.getPassword());       

    try {
        PreparedStatement pstLog = con.prepareStatement("SELECT * FROM teainfo_tbl WHERE tea_Em = ?");
        pstLog.setString(1, teaem);
        rs = pstLog.executeQuery();

        if (rs.next()) {
            String em = rs.getString("tea_Em");
            String password = rs.getString("tea_Pass");

            if ((teaem.equals(em)) && teapass.equals(password)) {
                JOptionPane.showMessageDialog(null, "SUCCESS");

                // Insert the email into tealogin_tbl
                try {
                    PreparedStatement pstInsert = con.prepareStatement("INSERT INTO tealogin_tbl (tea_Em) VALUES (?)");
                    pstInsert.setString(1, teaem);
                    pstInsert.executeUpdate();
                } catch (SQLException ex) {
                    // Handle the exception, e.g., display an error message
                    ex.printStackTrace();
                }

                new teacherMain().setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "INCORRECT!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "User not found!");
        }
    } catch (SQLException ex) {
        // Handle the exception, e.g., display an error message
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btn_tealoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        successClip.stop();
        new studentLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        successClip.stop();
        new adminLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if (jToggleButton1.isSelected()) {
            // If the toggle button is selected, mute
            successClip.stop();
            isMuted = true;
            jToggleButton1.setText("🔇");
        } else {
            // If the toggle button is not selected, unmute
            successClip.loop(Clip.LOOP_CONTINUOUSLY);
            isMuted = false;
            jToggleButton1.setText("🔈");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tealogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JTextField txt_teaem;
    private javax.swing.JPasswordField txt_teapass;
    // End of variables declaration//GEN-END:variables
}
