import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class teacherRegister extends javax.swing.JFrame {

    /**
     * Creates new form teacherRegister
     */
    public teacherRegister() {
        initComponents();
        Connect();

        LoadDeptNo();
        LoadCourseNo();
        LoadSubjectNo() ;
        
  
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    
    public void Connect(){
    
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/gradingsystem","root","");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(studentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    public void LoadCourseNo() {
        try {
            // Clear existing items in the combo box
            cmb_teadept.removeAllItems();
            cmb_regteadept.removeAllItems();

            // Retrieve the list of courses from the database
            String sql = "SELECT DISTINCT courses FROM dept_tbl";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();

            // Add each course to the combo box
            while (rs.next()) {
                cmb_teadept.addItem(rs.getString("courses"));
                cmb_regteadept.addItem(rs.getString("courses"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(adminMain.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
    
    
    
    
        public void LoadDeptNo() {
    try {
        // Clear existing items in the combo box
        cmb_regteadept.removeAllItems();

        // Retrieve the list of courses from the database
        String sql = "SELECT courses FROM dept_tbl";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();

        // Add each course to the combo box
        while (rs.next()) {
            cmb_regteadept.addItem(rs.getString("courses"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(adminMain.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }
        
        public void LoadSubjectNo() {
    try {
        // Clear existing items in the combo box
        cmb_regteasub.removeAllItems();
        
        String selectedDept = cmb_regteadept.getSelectedItem().toString();
        String selectedYear = cmb_regteayear.getSelectedItem().toString();

        // Retrieve the list of courses from the database
       
        PreparedStatement pstSubj = con.prepareStatement("SELECT * FROM subject_tbl WHERE stu_Dept = ? AND stu_Grade = ?");
        pstSubj.setString(1, selectedDept);
        pstSubj.setString(2, selectedYear);
        
        
        rs = pstSubj.executeQuery();

        // Add each course to the combo box
        while (rs.next()) {
            cmb_regteasub.addItem(rs.getString("sub_Name"));
        }
    } catch (SQLException ex) {
        Logger.getLogger(adminMain.class.getName()).log(Level.SEVERE, null, ex);
    }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_regteafname = new javax.swing.JTextField();
        txt_regteaid = new javax.swing.JTextField();
        txt_regteamname = new javax.swing.JTextField();
        txt_regtealname = new javax.swing.JTextField();
        cmb_regteayear = new javax.swing.JComboBox<>();
        cmb_regteasect = new javax.swing.JComboBox<>();
        cmb_regteadept = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmb_teaid = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_regteaidsearch = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_regtea = new javax.swing.JButton();
        txt_regteaem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_regteapass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmb_teadept = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmb_regteasect2 = new javax.swing.JComboBox<>();
        cmb_regteasect3 = new javax.swing.JComboBox<>();
        btn_serdept = new javax.swing.JButton();
        btn_updatetea = new javax.swing.JButton();
        cmb_regteasem = new javax.swing.JComboBox<>();
        cmb_regteasub = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher Registration");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_regteafname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regteafname.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txt_regteafname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 150, -1));

        txt_regteaid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regteaid.setForeground(new java.awt.Color(0, 51, 51));
        txt_regteaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regteaidActionPerformed(evt);
            }
        });
        txt_regteaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_regteaidKeyReleased(evt);
            }
        });
        jPanel1.add(txt_regteaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 150, -1));

        txt_regteamname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regteamname.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txt_regteamname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 150, -1));

        txt_regtealname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regtealname.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txt_regtealname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 150, -1));

        cmb_regteayear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteayear.setForeground(new java.awt.Color(0, 51, 51));
        cmb_regteayear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(cmb_regteayear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 150, 30));

        cmb_regteasect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteasect.setForeground(new java.awt.Color(0, 51, 51));
        cmb_regteasect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jPanel1.add(cmb_regteasect, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, 30));

        cmb_regteadept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteadept.setForeground(new java.awt.Color(0, 51, 51));
        cmb_regteadept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT", "CS", "FM" }));
        cmb_regteadept.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_regteadeptItemStateChanged(evt);
            }
        });
        cmb_regteadept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_regteadeptActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_regteadept, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 150, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(40);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 550, 630));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Department");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, 30));

        cmb_teaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_teaidActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_teaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 200, 150, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Teacher ID SELECT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 200, -1, 30));

        btn_regteaidsearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_regteaidsearch.setText("Search");
        btn_regteaidsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regteaidsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regteaidsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 200, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 30, 30));

        btn_regtea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_regtea.setText("Register Teacher");
        btn_regtea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regteaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regtea, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, -1, 30));

        txt_regteaem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regteaem.setForeground(new java.awt.Color(0, 51, 51));
        txt_regteaem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regteaemActionPerformed(evt);
            }
        });
        txt_regteaem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_regteaemKeyReleased(evt);
            }
        });
        jPanel1.add(txt_regteaem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 150, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, -1, 30));

        txt_regteapass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_regteapass.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(txt_regteapass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 150, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, -1, 30));

        cmb_teadept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_teadeptActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_teadept, new org.netbeans.lib.awtextra.AbsoluteConstraints(1002, 160, 150, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Section");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 520, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Year Level");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, -1, 30));

        cmb_regteasect2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteasect2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jPanel1.add(cmb_regteasect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, -1, 30));

        cmb_regteasect3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteasect3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        jPanel1.add(cmb_regteasect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, -1, 30));

        btn_serdept.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_serdept.setText("Search");
        btn_serdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serdeptActionPerformed(evt);
            }
        });
        jPanel1.add(btn_serdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 160, -1, 30));

        btn_updatetea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_updatetea.setText("Update Teacher");
        btn_updatetea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateteaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_updatetea, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 670, -1, 30));

        cmb_regteasem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteasem.setForeground(new java.awt.Color(0, 51, 51));
        cmb_regteasem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        cmb_regteasem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_regteasemActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_regteasem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 150, 30));

        cmb_regteasub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_regteasub.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(cmb_regteasub, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sem level");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Subject");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Search sub");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Department Select");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 160, -1, 30));

        jPanel2.setBackground(new java.awt.Color(63, 171, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Teacher Registration");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, 80));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 80));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cvsu logo.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 340, 300));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 150)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(63, 171, 46));
        jLabel20.setText("IMUS");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 630, 410, 170));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 154)); // NOI18N
        jLabel22.setText("IMUS");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 640, 410, 170));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, 30));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("List of Teacher");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 260, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(63, 171, 46));
        jLabel23.setText("Cavite State University");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 550, 60));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel24.setText("Cavite State University");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 580, 530, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_teadeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_teadeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_teadeptActionPerformed

    private void btn_regteaidsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regteaidsearchActionPerformed
        try {
        // Check if cmb_teaid is empty or no item is selected
        if (cmb_teaid.getItemCount() == 0 || cmb_teaid.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No Teacher IDs available. Please perform a search first.");
            return;
        }
        
        cmb_regteasub.removeAllItems();
        
         
        String dept = (String) cmb_teadept.getSelectedItem();
        String year = (String) cmb_regteayear.getSelectedItem();
        String sem = (String) cmb_regteasem.getSelectedItem();
        
        PreparedStatement pstSub = con.prepareStatement("SELECT * FROM subject_tbl WHERE stu_Dept=? AND stu_Grade = ? AND sem_Num = ?");
        
        pstSub.setString(1, dept);
        pstSub.setString(2, year);
        pstSub.setString(3, sem);
        
        
        rs = pstSub.executeQuery();
        
        while (rs.next()) {
        
            cmb_regteasub.addItem(rs.getString("sub_Name"));
            
        
        }
            // Retrieve the list of courses from the database
        
        

        String selectedTeaId = cmb_teaid.getSelectedItem().toString();

        pst = con.prepareStatement("SELECT * FROM teainfo_tbl WHERE tea_num=?");
        pst.setString(1, selectedTeaId);
        rs = pst.executeQuery();

        if (rs.next()) {
            // Populate the fields with the retrieved data
            txt_regteaid.setText(rs.getString(2));
            txt_regteafname.setText(rs.getString(3));
            txt_regteamname.setText(rs.getString(4));
            txt_regtealname.setText(rs.getString(5));
            txt_regteaem.setText(rs.getString(6));
            txt_regteapass.setText(rs.getString(7));
            
            
            

            cmb_regteadept.setSelectedItem(rs.getString(8));
            cmb_regteayear.setSelectedItem(rs.getString(9));
            cmb_regteasect.setSelectedItem(rs.getString(10));
            cmb_regteasect2.setSelectedItem(rs.getString(11));
            cmb_regteasect3.setSelectedItem(rs.getString(12));
            cmb_regteasub.setSelectedItem(rs.getString(13));
            cmb_regteasem.setSelectedItem(rs.getString(14));
      
            
        
        } else {
            JOptionPane.showMessageDialog(this, "No Record Found");
        }
    } catch (SQLException ex) {
        Logger.getLogger(teacherRegister.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_regteaidsearchActionPerformed

    private void btn_regteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regteaActionPerformed
            try {
            String tearegnum = txt_regteaid.getText();
            String tearegfname = txt_regteafname.getText();
            String tearegmname = txt_regteamname.getText();
            String teareglname = txt_regtealname.getText();
            String tearegdept = cmb_regteadept.getSelectedItem().toString();
            String tearegyear = cmb_regteayear.getSelectedItem().toString();
            String tearegsect = cmb_regteasect.getSelectedItem().toString();
            String tearegsect2 = cmb_regteasect2.getSelectedItem().toString();
            String tearegsect3 = cmb_regteasect3.getSelectedItem().toString();
            String tearegem = txt_regteaem.getText();           
            String tearegpass = txt_regteapass.getText();
            String teeasub = cmb_regteasub.getSelectedItem().toString();
            
            boolean isValidStudentNum = tearegnum.matches("^[0-9]*$") && tearegnum.length() == 9;
            boolean isValidEmail = tearegem.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$");
            
            PreparedStatement pstCheck = con.prepareStatement("SELECT * FROM teainfo_tbl WHERE tea_num = ? OR tea_em = ?");
            pstCheck.setString(1, tearegnum);
            pstCheck.setString(2, tearegem);

            ResultSet rsCheck = pstCheck.executeQuery();
            
            
            if(!isValidStudentNum || !isValidEmail){
            
            
               
            
                JOptionPane.showMessageDialog(this, "Invalid ID or Email!");
            
            
            }else if (rsCheck.next()){
                
                JOptionPane.showMessageDialog(this, "Teacher ID or Email Already exists!");
            }else{
            
            pst = con.prepareStatement("INSERT INTO teainfo_tbl (tea_num,tea_fname,tea_mname, tea_lname, tea_em, tea_pass, tea_dept,  tea_year, tea_sect,tea_sect2,tea_sect3,tea_sub) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1, tearegnum);
            pst.setString(2, tearegfname);
            pst.setString(3, tearegmname);
            pst.setString(4, teareglname);
            pst.setString(5, tearegem);
            pst.setString(6, tearegpass);
            pst.setString(7, tearegdept);
            pst.setString(8, tearegyear);
            pst.setString(9, tearegsect);
            pst.setString(10, tearegsect2);
            pst.setString(11, tearegsect3);
            pst.setString(12, teeasub);
            
            
          
            int k = pst.executeUpdate();
            
            if (k == 1){
                
                JOptionPane.showMessageDialog(this,"Data Addedd Successfully!");
                
                txt_regteaid.setText("");
                txt_regteafname.setText("");
                txt_regteamname.setText("");
                txt_regtealname.setText("");
                txt_regteaem.setText("");
                txt_regteapass.setText("");
                
                
            }else {
            
                JOptionPane.showMessageDialog(this,"Data Not recorder!");
                
            }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(studentRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_regteaActionPerformed

    private void txt_regteaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regteaidActionPerformed
        // TODO add your handling code here:
        String sturegnum = txt_regteaid.getText();
            
            if(sturegnum.matches("^[0-9]*$") && sturegnum.length()==9){
                
                txt_regteaid.setBackground(new Color(159,226, 191));
                
            }else {
                
                txt_regteaid.setBackground(new Color(255,120,120));
            }
    }//GEN-LAST:event_txt_regteaidActionPerformed

    private void btn_serdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serdeptActionPerformed
        // TODO add your handling code here:
        try {
            // Get the selected grade and section
            String selectedDept = (String) cmb_teadept.getSelectedItem();
           

            // SQL query to retrieve student IDs based on grade and section
            String query = "SELECT tea_num FROM teainfo_tbl WHERE tea_dept = ?";
            pst = con.prepareStatement(query);
            pst.setString(1, selectedDept);
            
            rs = pst.executeQuery();

            // Clear existing items in studentComboBox
            cmb_teaid.removeAllItems();

            // Add retrieved student IDs to studentComboBox
            while (rs.next()) {
                String teacherID = rs.getString("tea_num");
                cmb_teaid.addItem(teacherID);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(teacherMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_serdeptActionPerformed

    private void cmb_teaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_teaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_teaidActionPerformed

    private void btn_updateteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateteaActionPerformed
        // TODO add your handling code here:
        try {
            String teaupnum = txt_regteaid.getText();
            String teaupfname = txt_regteafname.getText();
            String teaupmname = txt_regteamname.getText();
            String teauplname = txt_regtealname.getText();
            String tearegdept = cmb_regteadept.getSelectedItem().toString();
               
 
            String teaupyear = cmb_regteayear.getSelectedItem().toString();
            String teaupem = txt_regteaem.getText();           
            String teaupass = txt_regteapass.getText();
            String teasect1 = (String) cmb_regteasect.getSelectedItem();
            String teasect2 = (String) cmb_regteasect2.getSelectedItem();
            String teasect3 = (String) cmb_regteasect3.getSelectedItem();

            pst = con.prepareStatement("UPDATE teainfo_tbl SET tea_num=?, tea_fname=?, tea_mname=?, tea_lname=?, tea_em=?, tea_pass=?, tea_dept=?, tea_year=?, tea_sect=?,tea_sect2=?, tea_sect3=? WHERE tea_num=?");
            pst.setString(1, teaupnum);
            pst.setString(2, teaupfname);
            pst.setString(3, teaupmname);
            pst.setString(4, teauplname);
            pst.setString(5, teaupem);
            pst.setString(6, teaupass);
            pst.setString(7, tearegdept);
            pst.setString(8, teaupyear);
            pst.setString(9, teasect1);
            pst.setString(10, teasect2);
            pst.setString(11, teasect3);
            
            // Set value for the 11th parameter
            pst.setString(12, teaupnum);

            int k = pst.executeUpdate();

            if (k==1){

                JOptionPane.showMessageDialog(this,"Record Updated Succeessfully!");
                txt_regteaid.setText("");
                txt_regteafname.setText("");
                txt_regteamname.setText("");
                txt_regtealname.setText("");
                txt_regteaem.setText("");
                txt_regteapass.setText("");
                
       
                

                txt_regteaid.requestFocus();
                
                



            } else{
            
                JOptionPane.showMessageDialog(this,"Record Failed to Update!");
            
            }

        } catch (SQLException ex) {
            Logger.getLogger(teacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_updateteaActionPerformed

    private void cmb_regteasemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_regteasemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_regteasemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        // Check if cmb_teaid is empty or no item is selected
            

            
            cmb_regteasub.removeAllItems();

            String dept = (String) cmb_regteadept.getSelectedItem();
            String year = (String) cmb_regteayear.getSelectedItem();
            String sem = (String) cmb_regteasem.getSelectedItem();

            PreparedStatement pstSub = con.prepareStatement("SELECT * FROM subject_tbl WHERE stu_Dept=? AND stu_Grade = ? AND sem_Num = ?");

            pstSub.setString(1, dept);
            pstSub.setString(2, year);
            pstSub.setString(3, sem);


            rs = pstSub.executeQuery();

            while (rs.next()) {
                
                cmb_regteasub.addItem(rs.getString("sub_Name"));
                


            }
                // Retrieve the list of courses from the database



            
        } catch (SQLException ex) {
            Logger.getLogger(teacherRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new adminMain().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_regteaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_regteaidKeyReleased
        // TODO add your handling code here:
        String sturegnum = txt_regteaid.getText();
            
            if(sturegnum.matches("^[0-9]*$") && sturegnum.length()==9){
                
                txt_regteaid.setBackground(new Color(159,226, 191));
                
            }else {
                
                txt_regteaid.setBackground(new Color(255,120,120));
            }
    }//GEN-LAST:event_txt_regteaidKeyReleased

    private void txt_regteaemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regteaemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regteaemActionPerformed

    private void txt_regteaemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_regteaemKeyReleased
        // TODO add your handling code here:
        String sturEmail = txt_regteaem.getText();
            
        if(sturEmail.matches("^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$")){

            txt_regteaem.setBackground(new Color(159,226, 191));

        }else {

            txt_regteaem.setBackground(new Color(255,120,120));
        }
    }//GEN-LAST:event_txt_regteaemKeyReleased

    private void cmb_regteadeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_regteadeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_regteadeptActionPerformed

    private void cmb_regteadeptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_regteadeptItemStateChanged
        
    }//GEN-LAST:event_cmb_regteadeptItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regtea;
    private javax.swing.JButton btn_regteaidsearch;
    private javax.swing.JButton btn_serdept;
    private javax.swing.JButton btn_updatetea;
    private javax.swing.JComboBox<String> cmb_regteadept;
    private javax.swing.JComboBox<String> cmb_regteasect;
    private javax.swing.JComboBox<String> cmb_regteasect2;
    private javax.swing.JComboBox<String> cmb_regteasect3;
    private javax.swing.JComboBox<String> cmb_regteasem;
    private javax.swing.JComboBox<String> cmb_regteasub;
    private javax.swing.JComboBox<String> cmb_regteayear;
    private javax.swing.JComboBox<String> cmb_teadept;
    private javax.swing.JComboBox<String> cmb_teaid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_regteaem;
    private javax.swing.JTextField txt_regteafname;
    private javax.swing.JTextField txt_regteaid;
    private javax.swing.JTextField txt_regtealname;
    private javax.swing.JTextField txt_regteamname;
    private javax.swing.JTextField txt_regteapass;
    // End of variables declaration//GEN-END:variables
}
